export const SELECT_BRAND = 'SELECT_BRAND';
export const SELECT_MODEL = 'SELECT_MODEL';
export const GET_VEHICLES = 'GET_VEHICLES';
export const GET_VEHICLES_SUCCESS = 'GET_VEHICLES_SUCCESS';
export const GET_PARTIALS = 'GET_PARTIALS';
export const GET_PARTIALS_SUCCESS = 'GET_PARTIALS_SUCCESS';
